config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'admin#index'
    resources :actors
    resources :topics
    resources :questions
    resources :actor_categories
    resources :users
  end

  root 'pages#index'
  get "/about" => "pages#about"
  get "/methodology" => "pages#methodology"
  get "/index" => "pages#index"
  get "/index" => "pages#index"
  resources :topics, only: [:index]
  resources :preferences, only: [:create]
  get 'compara-preferencias', to: 'topics#index'
  get 'marca-tu-preferencia', action: :choose_topic, controller: :preferences
  get 'preferences/choose_topic', action: :choose_topic, controller: :preferences
  get 'preferences/answer_questions', action: :answer_questions, controller: :preferences
  get 'preferences/your_preferences', action: :your_preferences, controller: :preferences
  devise_for :users

end

app/models/actor_category.rb
class ActorCategory < ApplicationRecord
  has_many :actors

  validates :name, presence: true
end

app/controllers/admin/actor_categories_controller.rb
class Admin::ActorCategoriesController < Admin::AdminController
  before_action :set_actor_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @actor_categories = ActorCategory.all
  end

  def show
  end

  def new
    @actor_category = ActorCategory.new
  end

  def edit
  end

  def create
    @actor_category = ActorCategory.new(actor_category_params)

    if @actor_category.save
      redirect_to admin_actor_category_url(@actor_category), notice: 'Actor category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @actor_category.update(actor_category_params)
      redirect_to admin_actor_category_url(@actor_category), notice: 'Actor category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @actor_category.destroy
    redirect_to admin_actor_categories_url, notice: 'Actor category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor_category
      @actor_category = ActorCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def actor_category_params
      params.require(:actor_category).permit(:name, :icon)
    end
end

app/views/admin/actor_categories/_form.html.erb
<%= simple_form_for [:admin, actor_category], html: { class: 'uk-form-horizontal uk-margin-large'} do |f| %>

  <div class="uk-margin">
    <%= f.label :name, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input :name, input_html: {class: 'uk-input'}, label: false %>
    </div>
  </div>

  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= f.button :submit, class: 'uk-button button-color-purple' %>
    </div>
  </div>

<% end %>

app/views/admin/actor_categories/edit.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Tipos de actores', admin_actor_categories_path %> </li>
  <li><span> <%= @actor_category.name%> </span></li>
</ul>

<h1>Editar Categoría de Actor</h1>

<%= render 'form', actor_category: @actor_category %>

app/views/admin/actor_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de actores</h1>

<%= link_to 'Nuevo tipo de actor', new_admin_actor_category_path %>

<table class="uk-table uk-table-justify uk-table-divider uk-table-middle">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cantidad de actores</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actor_categories.each do |actor_category| %>
      <tr>
        <td><%= actor_category.name %></td>
        <td><%= actor_category.actors.count %></td>
        <td><%= link_to 'Ver', admin_actor_category_path(actor_category) %></td>
        <td><%= link_to 'Editar', edit_admin_actor_category_path(actor_category) %></td>
        <td><%= link_to 'Eliminar', admin_actor_category_url(actor_category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/actor_categories/new.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Tipos de actores', admin_actor_categories_path %> </li>
  <li><span>Nueva categoría de actor</span></li>
</ul>

<h1>Nuevo tipo de actor</h1>

<%= render 'form', actor_category: @actor_category %>

app/views/admin/actor_categories/show.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Tipo de actores', admin_actor_categories_path %> </li>
  <li><span><%= @actor_category.name %></span></li>
</ul>

<p id="notice"><%= notice %></p>

<h2> <%= @actor_category.name %> </h2>

<ul class="uk-list uk-list-divider">
  <% @actor_category.actors.each do |a| %>
    <li> <%= link_to a.name, admin_actor_path(a) %> </li>
  <% end %>
</ul>