config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'admin#index'
    resources :actors
    resources :topics
    resources :questions
    resources :actor_categories
    resources :users
  end

  root 'pages#index'
  get "/about" => "pages#about"
  get "/methodology" => "pages#methodology"
  get "/index" => "pages#index"
  get "/index" => "pages#index"
  resources :topics, only: [:index]
  resources :preferences, only: [:create]
  get 'compara-preferencias', to: 'topics#index'
  get 'marca-tu-preferencia', action: :choose_topic, controller: :preferences
  get 'preferences/choose_topic', action: :choose_topic, controller: :preferences
  get 'preferences/answer_questions', action: :answer_questions, controller: :preferences
  get 'preferences/your_preferences', action: :your_preferences, controller: :preferences
  devise_for :users

end

app/models/topic.rb
class Topic < ApplicationRecord
  resourcify

  has_many :questions
  has_one_attached :icon

  validates :name, uniqueness: { case_sensitive: false }
  validates :name, presence: true

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::AdminController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /topics
  def index
    @topics = Topic.all.order(:name)
  end

  # GET /topics/1
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to admin_topic_url(@topic), notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to admin_topic_url(@topic), notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to admin_topics_url, notice: 'Topic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit(:name, :icon)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /topics
  def index
    request.variant = determine_variant
    @topics = Topic.includes(questions: [positions: [actor_positions: [:actor, :position]]]).order(:name)

  end

  # GET /topics/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit(:title)
    end

    def determine_variant
      variant = :desktop
      # some code to determine the variant(s) to use
      variant = :mobile if browser.device.mobile?
      variant
    end

end

app/views/admin/topics/_form.html.erb
<%= simple_form_for [:admin, @topic], html: { class: 'uk-form-horizontal uk-margin-large'} do |f| %>
  <div class="uk-margin">
    <%= f.label :name, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input :name, input_html: {class: 'uk-input'}, label: false %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :icon, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <% if @topic.icon.attached? %>
        <label class="uk-button uk-button-default ">
          Subir desde tu computador
          <span style="display:none;">
            <%= f.input_field :icon, as: :file %>
          </span>
        </label>
        <br>
        Icono actual: <img src="<%= url_for(@topic.icon) %>" width="40" height="40" uk-svg>
      <% else %>
        <label class="uk-button uk-button-default ">
          Subir desde tu computador
          <span style="display:none;">
            <%= f.input_field :icon, as: :file %>
          </span>
        </label>
      <% end %>
    </div>
  </div>

  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= f.button :submit, class: 'uk-button button-color-purple' %>
    </div>
  </div>
<% end %>

app/views/admin/topics/edit.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Categorías', admin_topics_path %> </li>
  <li><span><%= @topic.name %></span></li>
</ul>

<h1>Editar Categoría</h1>

<div class="uk-container">
  <%= render 'form', topic: @topic %>
</div>

app/views/admin/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>

<%= link_to 'Nueva categoría', new_admin_topic_path %>

<table class="uk-table uk-table-justify uk-table-divider uk-table-middle">
  <thead>
    <tr>
      <th> Icono</th>
      <th> Nombre </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td>
          <% if topic.icon.attached? %>
            <img src="<%= url_for(topic.icon) %>" width="40" height="40" uk-svg>
          <% end %>
        </td>
        <td><%= topic.name %></td>
        <td><%= link_to 'Ver', admin_topic_path(topic) %></td>
        <td><%= link_to 'Editar', edit_admin_topic_path(topic) %></td>
        <td><%= link_to 'Eliminar', admin_topic_url(topic), method: :delete, data: { confirm: '¿Estas segura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/topics/new.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Categorías', admin_topics_path %> </li>
  <li><span>Nueva categoría></span></li>
</ul>

<h1>Nueva Categoría</h1>

<div class="uk-container">
  <%= render 'form', topic: @topic %>
</div>

app/views/admin/topics/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="uk-breadcrumb">
  <li> <%= link_to 'Temas', admin_topics_path %> </li>
  <li><span><%= @topic.name %></span></li>
</ul>

<h2> <%= @topic.name %> </h2>

<p> Icono: </p>
<% if @topic.icon.attached? %>
  <img src="<%= url_for(@topic.icon) %>" width="40" height="40" uk-svg>
<% end %>


<%= link_to 'Edit', edit_admin_topic_path(@topic) %> |
<%= link_to 'Back', admin_topics_path %>