config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'admin#index'
    resources :actors
    resources :topics
    resources :questions
    resources :actor_categories
    resources :users
  end

  root 'pages#index'
  get "/about" => "pages#about"
  get "/methodology" => "pages#methodology"
  get "/index" => "pages#index"
  get "/index" => "pages#index"
  resources :topics, only: [:index]
  resources :preferences, only: [:create]
  get 'compara-preferencias', to: 'topics#index'
  get 'marca-tu-preferencia', action: :choose_topic, controller: :preferences
  get 'preferences/choose_topic', action: :choose_topic, controller: :preferences
  get 'preferences/answer_questions', action: :answer_questions, controller: :preferences
  get 'preferences/your_preferences', action: :your_preferences, controller: :preferences
  devise_for :users

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  def index
    @users = User.all.order(:email)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_url(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, role_ids: [])
    end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user], html: { class: 'uk-form-horizontal uk-margin-large'} do |f| %>

  <div class="uk-margin">
    <%= f.label :email, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input :email, label: false, input_html: {class: 'uk-input'} %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :password, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input :password, label: false, input_html: {class: 'uk-input'} %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :roles, class: 'uk-form-label uk-margin-remove' %>
    <%= f.association :roles, label: false, wrapper_html: {class: 'uk-form-controls'}, item_wrapper_tag: 'div', input_html: {class: "uk-select" } %>
  </div>

  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= f.button :submit, class: 'uk-button button-color-purple' %>
    </div>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Usuarias', admin_users_path %> </li>
  <li><span><%= @user.email %></span></li>
</ul>

<h1>Editar Usuaria</h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<%= link_to 'Nueva usuaria', new_admin_user_path %>

<table class="uk-table uk-table-justify uk-table-divider uk-table-middle">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.roles.map{ |x| x.name} %></td>
        <td><%= link_to 'Ver', admin_user_path(user) %></td>
        <td><%= link_to 'Editar', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Eliminar', admin_user_url(user), method: :delete, data: { confirm: '¿Confirmas que deseas eliminar la usuaria?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/users/new.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Usuarias', admin_users_path %> </li>
  <li><span>Nueva usuaria</span></li>
</ul>

<h1> Nueva Usuaria</h1>

<div class="uk-container">
  <%= render 'form', user: @user %>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="uk-breadcrumb">
  <li> <%= link_to 'Usuarias', admin_users_path %> </li>
  <li><span><%= @user.email %></span></li>
</ul>

<h1 class="uk-margin-remove"> <%= @user.email %> </h1>

<div class="uk-container uk-text-right uk-padding">
  <%= link_to 'Editar', edit_admin_user_path(@user), class: 'uk-button button-color-purple' %>
</div>