config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/' => 'admin#index'
    resources :actors
    resources :topics
    resources :questions
    resources :actor_categories
    resources :users
  end

  root 'pages#index'
  get "/about" => "pages#about"
  get "/methodology" => "pages#methodology"
  get "/index" => "pages#index"
  get "/index" => "pages#index"
  resources :topics, only: [:index]
  resources :preferences, only: [:create]
  get 'compara-preferencias', to: 'topics#index'
  get 'marca-tu-preferencia', action: :choose_topic, controller: :preferences
  get 'preferences/choose_topic', action: :choose_topic, controller: :preferences
  get 'preferences/answer_questions', action: :answer_questions, controller: :preferences
  get 'preferences/your_preferences', action: :your_preferences, controller: :preferences
  devise_for :users

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administración Chile marca preferencia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="uk-grid-small uk-flex-center" uk-grid>

      <div class="uk-width-1-4@s">
        <ul class="uk-nav-default uk-nav-parent-icon uk-padding" uk-nav>
          <li class="uk-active"><a href="#">Resumen</a></li>
          <li> <%= link_to 'Categorías', admin_topics_path %></li>
          <li> <%= link_to 'Preguntas', admin_questions_path %></li>
          <li> <%= link_to 'Tipos de actores', admin_actor_categories_path %></li>
          <li> <%= link_to 'Actores', admin_actors_path %></li>
          <li> <%= link_to 'Administradoras', admin_users_path %></li>

          <li class="uk-nav-divider"></li>

          <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path) %>
            </li>
          <% end %>

        </ul>
      </div>

      <div class="uk-width-3-4@s">
        <div class="uk-container">
          <%= yield %>
        </div>
      </div>

    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= if content_for?(:title) then yield(:title) + ' | ' end %> Chile marca preferencia </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name='description' content='<%= yield_meta_tag(:description, 'Compara aquí las posturas de distintos actores políticos para Chile a raíz del plebiscito 2020 ') %>'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <%= favicon_link_tag asset_path('favicon.ico') %>

    <!-- Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= yield_meta_tag(:url, root_url) %>">
    <meta property="og:title" content="<%= if content_for?(:title) then yield(:title) + ' | ' end %> Chile marca preferencia">
    <meta property="og:description" content="<%= yield_meta_tag(:description, 'Compara aquí las posturas de distintos actores políticos para Chile a raíz del plebiscito 2020 ') %>">
    <meta property="og:image" content="<%= yield_meta_tag(:image_to_share, asset_path('og-img.png')) %>">

    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <!-- Twitter -->
    <meta name="twitter:title" content="<%= if content_for?(:title) then yield(:title) + ' | ' end %> Chile marca preferencia">
    <meta name="twitter:description" content="<%= yield_meta_tag(:description, 'Compara aquí las posturas de distintos actores políticos para Chile a raíz del plebiscito 2020 ') %>">
    <meta name="twitter:image" content="<%= yield_meta_tag(:image_to_share_twitter, asset_path('og-img.png')) %>">
    <meta name="twitter:card" content="summary_large_image">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-180911672-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-180911672-1');
    </script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>


</html>